# NumPy
* https://numpy.org/doc/stable/index.html

In [2]:
import numpy as np
np.__version__

'2.5.2'

# Modules

In [3]:
np.__numpy_submodules__

{'char',
 'core',
 'ctypeslib',
 'dtypes',
 'exceptions',
 'f2py',
 'fft',
 'lib',
 'linalg',
 'ma',
 'polynomial',
 'random',
 'rec',
 'strings',
 'test',
 'testing',
 'typing'}

In [6]:
# # properties in `np`
# for idx, s in enumerate(dir(np)):
#   if idx > 0 and idx % 10 == 0:
#     print(f"{s}", end="\n")
#   else:
#     print(s, end=" ")

# print("""| Category    | Method       | Description |
# | :---------- | :----------- | :---------- |""")
# for p in dir(np):
#   if not p.startswith('__'):
#     print(
#         f'||{p}||')

# ufuncs

In [1]:
from scipy import special
dir(special)

['SpecialFunctionError',
 'SpecialFunctionWarning',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_basic',
 '_comb',
 '_ellip_harm',
 '_ellip_harm_2',
 '_gufuncs',
 '_input_validation',
 '_lambertw',
 '_logsumexp',
 '_multiufuncs',
 '_orthogonal',
 '_sf_error',
 '_specfun',
 '_special_ufuncs',
 '_spfun_stats',
 '_spherical_bessel',
 '_support_alternative_backends',
 '_ufunc_tools',
 '_ufuncs',
 '_ufuncs_cxx',
 'add_newdocs',
 'agm',
 'ai_zeros',
 'airy',
 'airye',
 'assoc_laguerre',
 'assoc_legendre_p',
 'assoc_legendre_p_all',
 'basic',
 'bdtr',
 'bdtrc',
 'bdtri',
 'bdtrik',
 'bdtrin',
 'bei',
 'bei_zeros',
 'beip',
 'beip_zeros',
 'ber',
 'ber_zeros',
 'bernoulli',
 'berp',
 'berp_zeros',
 'besselpoly',
 'beta',
 'betainc',
 'betaincc',
 'betainccinv',
 'betaincinv',
 'betaln',
 'bi_zeros',
 'binom',
 'boxcox',
 'boxcox1p',
 'btdtria',
 'btdtrib',
 'c_roots',
 'cbrt',
 'cg_roots',
 'chdtr'

# Linear Algebra

In [8]:
from numpy import linalg as LA

import pprint

In [ ]:
# 矩阵和向量积
A = np.arange(9).reshape(3,3)
B = np.arange(12).reshape(3,4)

pprint.pprint(A)
pprint.pprint(B)

pprint.pprint(A.dot(B))        # 数组点积
pprint.pprint(np.dot(A, B))
pprint.pprint(np.matmul(A, B)) # 矩阵积


a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
pprint.pprint(np.vdot(a,b))  # 向量点积
pprint.pprint(np.inner(a,b)) # 向量内积
pprint.pprint(np.outer(a,b)) # 向量外积

# 分解

A = np.arange(16).reshape(4,4)
q, r = LA.qr(A, mode='complete')
pprint.pprint(q)
pprint.pprint(r)
np.allclose(A, np.dot(q,r))

# 特征值

A = np.diag((1, 2, 3))
w, v = LA.eig(A)
pprint.pprint(w) # 特征值
pprint.pprint(v) # 特征向量
pprint.pprint(A @ v[0])
pprint.pprint(w[0] * v[0])
np.allclose(A @ v[0], w[0] * v[0])

# 范式


# 方程求解和矩阵逆

A = np.array([[[1., 2.], [3., 4.]], [[1, 3], [3, 5]]])
Ainv = LA.inv(A)
pprint.pprint(np.dot(A, Ainv))
np.allclose(A @ Ainv, np.eye(2))

# 异常


# 多个矩阵上的线性代数


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])
array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])
array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])
np.int64(130)
np.int64(130)
array([[ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20],
       [18, 21, 24, 27, 30],
       [24, 28, 32, 36, 40],
       [30, 35, 40, 45, 50]])
array([[ 0.        , -0.83666003, -0.17522784, -0.51893661],
       [-0.26726124, -0.47809144,  0.62042963,  0.56130836],
       [-0.53452248, -0.11952286, -0.71517574,  0.43419311],
       [-0.80178373,  0.23904572,  0.26997395, -0.47656486]])
array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
        -1.97773319e+01],
       [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
        -3.58568583e+00],
       [ 0.00000

True

: 

# Cleanup